# VertexOS Hyprland glass profile.
# Premium, minimal, fluid: restrained opacity, liquid blur, soft shadow, clean corners.

general {
    border_size = 1
    gaps_in = 6
    gaps_out = 14

    col.active_border = rgba(69d2ffee)
    col.inactive_border = rgba(ffffff22)
}

decoration {
    rounding = 12

    active_opacity = 0.95
    inactive_opacity = 0.85
    fullscreen_opacity = 1.0

    drop_shadow = true
    shadow_range = 20
    shadow_render_power = 3
    shadow_ignore_window = true
    col.shadow = rgba(00000055)
    col.shadow_inactive = rgba(00000024)

    blur {
        enabled = true
        size = 8
        passes = 3
        new_optimizations = true
        ignore_opacity = true
        vibrancy = 0.17
    }
}

animations {
    enabled = true

    bezier = vertexOpen, 0.16, 1.0, 0.3, 1.0
    bezier = vertexClose, 0.7, 0.0, 0.84, 0.0
    bezier = vertexSoft, 0.22, 1.0, 0.36, 1.0

    animation = windowsIn, 1, 5, vertexOpen, popin 88%
    animation = windowsOut, 1, 4, vertexClose, popin 92%
    animation = windowsMove, 1, 4, vertexSoft
    animation = border, 1, 4, vertexSoft
    animation = fade, 1, 4, vertexSoft
    animation = workspaces, 1, 5, vertexSoft, slide
}

$mod = SUPER
bind = $mod, Escape, exec, hyprlock
